/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.ArrayLinearList;
import modelo.Plato;

/**
 *
 * @author Asus
 */
public class crear_plato extends javax.swing.JFrame {

    public static ArrayLinearList <Plato> menu = Login.menu;
    /**
     * Creates new form crear_plato
     */
    public crear_plato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ingrediente1 = new javax.swing.JComboBox<>();
        Ingrediente2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Ingrediente3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Ingrediente4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Ingrediente5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Ingrediente6 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Ingrediente7 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Ingrediente8 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Ingrediente9 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Ingrediente10 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Cantidad1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Cantidad2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Cantidad3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Cantidad4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Cantidad5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Cantidad6 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Cantidad7 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Cantidad8 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Cantidad9 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Cantidad10 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        jLabel3.setText("Ingrediente1:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR   PLATO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 260, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrediente1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        Ingrediente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingrediente1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ingrediente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 203, -1));

        jPanel1.add(Ingrediente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 203, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrediente2:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jPanel1.add(Ingrediente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 203, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrediente3:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jPanel1.add(Ingrediente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 203, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrediente4:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jPanel1.add(Ingrediente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 203, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrediente5:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jPanel1.add(Ingrediente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 203, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrediente6:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jPanel1.add(Ingrediente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 203, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrediente7:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jPanel1.add(Ingrediente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 203, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ingrediente8:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jPanel1.add(Ingrediente9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 203, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrediente9:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jPanel1.add(Ingrediente10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 203, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingrediente10:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cantidad:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cantidad:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cantidad:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cantidad:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cantidad:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cantidad:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cantidad:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cantidad:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cantidad:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        Cantidad1.setText("nulo");
        jPanel1.add(Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 59, -1));

        jLabel24.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("gr.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        Cantidad2.setText("nulo");
        jPanel1.add(Cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 59, -1));

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("gr.");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        Cantidad3.setText("nulo");
        jPanel1.add(Cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 59, -1));

        jLabel26.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("gr.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        Cantidad4.setText("nulo");
        jPanel1.add(Cantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 59, -1));

        jLabel27.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("gr.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        Cantidad5.setText("nulo");
        jPanel1.add(Cantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 59, -1));

        jLabel28.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("gr.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        Cantidad6.setText("nulo");
        jPanel1.add(Cantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 59, -1));

        jLabel29.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("gr.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        Cantidad7.setText("nulo");
        jPanel1.add(Cantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 59, -1));

        jLabel30.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("gr.");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        Cantidad8.setText("nulo");
        jPanel1.add(Cantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 59, -1));

        jLabel31.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("gr.");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        Cantidad9.setText("nulo");
        jPanel1.add(Cantidad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 59, -1));

        jLabel32.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("gr.");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        Cantidad10.setText("nulo");
        jPanel1.add(Cantidad10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 59, -1));

        jLabel33.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("gr.");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        btnAtras.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        btnCrear.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btnCrear.setText("CREAR");
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 116, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 70, 30));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen.png"))); // NOI18N
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void Ingrediente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingrediente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingrediente1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Cantidad1;
    public javax.swing.JTextField Cantidad10;
    public javax.swing.JTextField Cantidad2;
    public javax.swing.JTextField Cantidad3;
    public javax.swing.JTextField Cantidad4;
    public javax.swing.JTextField Cantidad5;
    public javax.swing.JTextField Cantidad6;
    public javax.swing.JTextField Cantidad7;
    public javax.swing.JTextField Cantidad8;
    public javax.swing.JTextField Cantidad9;
    public javax.swing.JComboBox<String> Ingrediente1;
    public javax.swing.JComboBox<String> Ingrediente10;
    public javax.swing.JComboBox<String> Ingrediente2;
    public javax.swing.JComboBox<String> Ingrediente3;
    public javax.swing.JComboBox<String> Ingrediente4;
    public javax.swing.JComboBox<String> Ingrediente5;
    public javax.swing.JComboBox<String> Ingrediente6;
    public javax.swing.JComboBox<String> Ingrediente7;
    public javax.swing.JComboBox<String> Ingrediente8;
    public javax.swing.JComboBox<String> Ingrediente9;
    public javax.swing.JTextField Nombre;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}




