/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Image;
import java.awt.Toolkit;
import modelo.MinHeap;
import modelo.Producto;



/**
 *
 * @author windows 10
 */
public class CrearUsers extends javax.swing.JFrame {
    
    public static MinHeap <Producto> bodega = new MinHeap <>( );
    /**
     * Creates new form mainWindow
     */
    public CrearUsers() { 
        
        initComponents();        
        jDialog1.setLocationRelativeTo(null);
        
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalir2 = new javax.swing.JButton();
        jButtonLogin2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUser2 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Las contraseñas no coinciden");
        jDialog1.getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir2.setBackground(new java.awt.Color(255, 153, 153));
        jButtonSalir2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSalir2.setText("Salir");
        jButtonSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 30));

        jButtonLogin2.setBackground(new java.awt.Color(255, 153, 153));
        jButtonLogin2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLogin2.setText("Crear");
        jButtonLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin2ActionPerformed(evt);
            }
        });
        jButtonLogin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLogin2KeyPressed(evt);
            }
        });
        getContentPane().add(jButtonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 100, 30));

        jLabel13.setBackground(new java.awt.Color(255, 153, 153));
        jLabel13.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contraseña :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 153, 153));
        jLabel14.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Usuario :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jTextFieldUser2.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldUser2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jTextFieldUser2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 130, 30));

        jPasswordField4.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField4.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 130, 30));

        jPasswordField5.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField5.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 130, -1));

        jLabel15.setBackground(new java.awt.Color(255, 153, 153));
        jLabel15.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Repita Contraseña :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RESTAURANTE EL BACAN ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir2ActionPerformed
 System.exit(0);             // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir2ActionPerformed

    private void jButtonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogin2ActionPerformed

    private void jButtonLogin2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLogin2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogin2KeyPressed

    private void jTextFieldUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser2ActionPerformed

    private void jPasswordField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField4ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonLogin2;
    public javax.swing.JButton jButtonSalir2;
    public javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPasswordField jPasswordField4;
    public javax.swing.JPasswordField jPasswordField5;
    public javax.swing.JTextField jTextFieldUser2;
    // End of variables declaration//GEN-END:variables
}
