/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Brayan Estupiñan
 */
public class Inventario extends javax.swing.JFrame {
    
    private DefaultTableModel  modelo;
    int contador=0; 
    
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        CargarInterfaz();
        CargarDatos();
        this.setLocationRelativeTo(null);
    }

    public void CargarInterfaz(){
    String datos[][]={};
    String columna[]={"Nombre","cantidad","Precio"};
    modelo=new DefaultTableModel(datos,columna);
    TablaDatos.setModel(modelo);
    }
    
    public  void CargarDatos(){
    Producto p;
    for(int i=1; i<= Almacen.bodega.size();i++){
    p=Almacen.bodega.getNode(i);
    modelo.insertRow(i-1, new Object[]{});
    modelo.setValueAt(p.getNombre(), i-1,0);
    modelo.setValueAt(p.getCantidad(), i-1,1);
    modelo.setValueAt(p.getCosto(), i-1,2);
    }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 447, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Productos en inventario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 23, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventario-de-perdida.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 480, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

  
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
