/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Container;

/**
 *
 * @author Asus
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    

    
    
    public MenuPrincipal() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mostrar = new javax.swing.JButton();
        crearPlato = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(605, 459));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("MENU");

        mostrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mostrar.setText("VER");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        crearPlato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        crearPlato.setText("CREAR PLATO");
        crearPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(crearPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        Mostrar panel2=new Mostrar();
        panel2.setSize(600,600);
        panel2.setLocation(50,0);

        Menu.contenedor.removeAll();
        Menu.contenedor.add(panel2,BorderLayout.CENTER);
        Menu.contenedor.revalidate();
        Menu.contenedor.repaint();
    }//GEN-LAST:event_mostrarActionPerformed

    private void crearPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPlatoActionPerformed
        // TODO add your handling code here:
        crearPlato panel1=new crearPlato();
        panel1.setSize(750,500);
        panel1.setLocation(50, 0);
        //725,498
        Menu.contenedor.removeAll();
        Menu.contenedor.add(panel1,BorderLayout.CENTER);
        Menu.contenedor.revalidate();
        Menu.contenedor.repaint();
    }//GEN-LAST:event_crearPlatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrar;
    // End of variables declaration//GEN-END:variables
}
